import 'package:basecode/models/Message.dart';

List<Message> messages = [
  Message(
      1,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      2,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      3,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      4,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      5,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      6,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      7,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      8,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      9,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      10,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      11,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      1,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      2,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      3,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      4,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      5,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      6,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      7,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      8,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      9,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      10,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      11,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      1,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      2,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      3,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      4,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      5,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      6,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      7,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      8,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      9,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      true),
  Message(
      10,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
  Message(
      11,
      "Austin Rosario",
      "Keegan Sicat",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      false),
];
